### ISSUE TITLE
Would you please illustrate more on the loss function of D & R networks?

### ISSUE THREAD

**Issue by yikuan8** [microsoft/med-deadend#4]
Hello,

I am kind of confused on understanding the loss function of the DQN networks( line 122 thru 125 in RL.py). Would you please explain a bit? Thank you!

**Comment by twkillian** [comment]
This is an implementation of the [Huber loss ](https://en.wikipedia.org/wiki/Huber_loss) which is one of several standard losses used in Deep RL.
