### ISSUE TITLE
Would you please explain some about learning rate

### ISSUE THREAD

**Issue by yss858** [microsoft/med-deadend#5]
Hello
I see in your paper that the learning rate of the best SC-network is 5e-4 and epochs are 600. Then I see that the learning rate of the config.yaml file is 1e-4 and epochs are 400. Would you please let me know whether you use the former or the latter in the experiment? Thank you！

**Comment by twkillian** [comment]
So, after conferring with @fatemi, we've realized that our paper has this slight error. All experiments in the paper were produced by the code in this repository. So to accurately replicate what we've done, use the configuration file as currently provided.
